# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sami/Desktop/Semester8/ELE882/Brizi/bestphoto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sami/Desktop/Semester8/ELE882/Brizi/bestphoto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sami/Desktop/Semester8/ELE882/Brizi/bestphoto/CMakeFiles /Users/sami/Desktop/Semester8/ELE882/Brizi/bestphoto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sami/Desktop/Semester8/ELE882/Brizi/bestphoto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImageEnhancment

# Build rule for target.
ImageEnhancment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImageEnhancment
.PHONY : ImageEnhancment

# fast build rule for target.
ImageEnhancment/fast:
	$(MAKE) -f CMakeFiles/ImageEnhancment.dir/build.make CMakeFiles/ImageEnhancment.dir/build
.PHONY : ImageEnhancment/fast

ImageEnhancment.o: ImageEnhancment.cpp.o
.PHONY : ImageEnhancment.o

# target to build an object file
ImageEnhancment.cpp.o:
	$(MAKE) -f CMakeFiles/ImageEnhancment.dir/build.make CMakeFiles/ImageEnhancment.dir/ImageEnhancment.cpp.o
.PHONY : ImageEnhancment.cpp.o

ImageEnhancment.i: ImageEnhancment.cpp.i
.PHONY : ImageEnhancment.i

# target to preprocess a source file
ImageEnhancment.cpp.i:
	$(MAKE) -f CMakeFiles/ImageEnhancment.dir/build.make CMakeFiles/ImageEnhancment.dir/ImageEnhancment.cpp.i
.PHONY : ImageEnhancment.cpp.i

ImageEnhancment.s: ImageEnhancment.cpp.s
.PHONY : ImageEnhancment.s

# target to generate assembly for a file
ImageEnhancment.cpp.s:
	$(MAKE) -f CMakeFiles/ImageEnhancment.dir/build.make CMakeFiles/ImageEnhancment.dir/ImageEnhancment.cpp.s
.PHONY : ImageEnhancment.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ImageEnhancment"
	@echo "... ImageEnhancment.o"
	@echo "... ImageEnhancment.i"
	@echo "... ImageEnhancment.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

